#!/bin/sh

CURRENT_DIR=`dirname "${BASH_SOURCE-$0}"`

if [ $CURRENT_DIR != "." ]; then
	echo "the compile command must be run under the folder it exist"
	exit
fi

if [ $# -eq 1 ]; then
	SOURCE_FILE=$1
	DEST_FILE="`echo $1|cut -d'.' -f 1`.html"
	POST_FILE_NAME=${DEST_FILE#*\/}
	echo "transform $SOURCE_FILE to $DEST_FILE with pandoc"
	# pandoc -s --toc --template=templates/post -V post-file-name=$POST_FILE_NAME -f markdown -t html $SOURCE_FILE > $DEST_FILE
	pandoc -s --template=templates/p -V post-file-name=$DEST_FILE -f markdown -t html $SOURCE_FILE > $DEST_FILE
#	amm recommends.sc $DEST_FILE
	java -jar /Users/fq/workspace.keevol/afoo_blog_recommender/target/afoo-blog-recommender-1.0.0-SNAPSHOT.jar $DEST_FILE
else
	echo "the file to be transformed must be provided"
fi
